# Generated by Django 4.0.4 on 2022-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
