# Generated by Django 4.0.4 on 2022-04-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='invoice_detail',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='invoice_id',
            field=models.ManyToManyField(to='App.invoice'),
        ),
    ]
