# Generated by Django 4.0.4 on 2022-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_clients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
